export { ReactComponent as InfoIcon } from './svgs/info-icon.svg'
export { ReactComponent as MoadataLogo } from './svgs/moadataLogo.svg'
export { ReactComponent as LoginMailIcon } from './svgs/login-mail.svg'
export { ReactComponent as LoginLockIcon } from './svgs/login-lock.svg'
export { ReactComponent as PasswordEye } from './svgs/eye-solid.svg'
export { ReactComponent as PasswordSlashEye } from './svgs/eye-slash-solid.svg'
